version: "3"

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp

    environment:
      TZ: 'Africa/Johannesburg'
      WEBPASSWORD: 'password'

    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    

    cap_add:
      - NET_ADMIN

    restart: unless-stopped

  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - SERVERPORT=51820
      - PEERS=5
      - PEERDNS=1.1.1.1
      - ALLOWEDIPS=0.0.0.0/0 #Peer addresses allowed
      - INTERNAL_SUBNET=10.244.20.0/24 #Subnet used in VPN tunnel
      - SERVERURL=10.70.1.234 #Wireguard VPN server address

    volumes:
      - /opt/wireguard-server/config:/config
      - /usr/src:/usr/src 
      - /lib/modules:/lib/modules

    ports:
      - 51820:51820/udp
      
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    
    restart: unless-stopped