version: "2.1"

services:

  heimdall1:
    image: linuxserver/heimdall
    container_name: heimdall1
    volumes:
      - /home/wannock/appdata/heimdall1:/config
    environment:
      - PUID=998
      - PGID=100
      - TZ=Africa/Johannesburg
    ports:
      - 6941:80
      - 443:443
    restart: unless-stopped
  
  heimdall2:
    image: linuxserver/heimdall
    container_name:  heimdall2
    volumes:
      - /home/wannock/appdata/heimdall2:/config
    environment:
      - PUID=998
      - PGID=100
      - TZ=Africa/Johannesburg
    ports:
      - 6942:80
      - 444:443
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      - TZ:"Africa/Johannesburg"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    volumes:
      - /home/wannock/appdata/portainer:/config
    ports:
      - 9000:9000
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    volumes:
      - /home/wannock/appdata/wireguard:/config
    ports:
      - 51820:51820/udp
    restart: unless-stopped

  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    volumes:
      - /home/wannock/appdata/yacht:/config
    environment:
      - PUID=998
      - PGID=100
    ports:
      - 8001:8001
    restart: unless-stopped   