version: "2.1"

services:

  heimdall1:
    image: linuxserver/heimdall
    container_name: heimdall1
    volumes:
      - /home/wannock/appdata/heimdall1:/config
    environment:
      - PUID=998
      - PGID=100
      - TZ=Africa/Johannesburg
    ports:
      - 6941:80
      - 443:443
    restart: unless-stopped
  
  heimdall2:
    image: linuxserver/heimdall
    container_name:  heimdall2
    volumes:
      - /home/wannock/appdata/heimdall2:/config
    environment:
      - PUID=998
      - PGID=100
      - TZ=Africa/Johannesburg
    ports:
      - 6942:80
      - 444:443
    restart: unless-stopped
