version: "2.1"

services:

  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    volumes:
      - /home/wannock/appdata/yacht:/config
    environment:
      - PUID=998
      - PGID=100
    ports:
      - 8001:8001
    restart: unless-stopped
    