version: "2.1"

services:

  heimdall1:
    image: linuxserver/heimdall
    container_name: heimdall1
    volumes:
      - /home/wannock/appdata/heimdall1:/config
    environment:
      - PUID=998
      - PGID=100
      - TZ=Africa/Johannesburg
    ports:
      - 6941:80
      - 443:443
    restart: unless-stopped
  
  heimdall2:
    image: linuxserver/heimdall
    container_name:  heimdall2
    volumes:
      - /home/wannock/appdata/heimdall2:/config
    environment:
      - PUID=998
      - PGID=100
      - TZ=Africa/Johannesburg
    ports:
      - 6942:80
      - 444:443
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      - TZ:"Africa/Johannesburg"
    ports:
      - "54:53/tcp"
      - "55:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    restart: unless-stopped

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - SERVERPORT=51820 #optional
      - PEERS=15 #optional
      - PEERDNS=auto 1.1.1.1
      - ALLOWEDIPS=0.0.0.0/0 #Peer addresses allowed
      - INTERNAL_SUBNET=10.244.20.0/24 #Subnet used in VPN tunnel
      - SERVERURL=10.70.1.251 #Wireguard VPN server address
    volumes:
      - /home/wannock/appdata/wireguard-server/config:/config
      - /usr/src:/usr/src # location of kernel headers
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    volumes:
      - /home/wannock/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    restart: unless-stopped

